### ISSUE TITLE
The lab repository couldn't open ! (even after I forked as suggested in top right corner)

### ISSUE THREAD

**Issue by Peramanathan** [learn-co-curriculum/first-lab-ruby-learn-cli-nitrous#10]

**Comment by AnnJohn** [comment]
Hi @Peramanathan for immediate help with labs, please use the Ask a Question tool in Learn and someone from our instructor support team will get back to you right away. Thanks!

**Comment by Peramanathan** [comment]
@AnnJohn : Thanks ! I have fixed it directly from nitorus ide terminal. `learn open` does the trick :)

**Comment by AnnJohn** [comment]
@Peramanathan Great!
