### ISSUE TITLE
404 Not Found when Opening the nitrous console

### ISSUE THREAD

**Issue by avrahamluna** [learn-co-curriculum/first-lab-ruby-learn-cli-nitrous#11]
there appears to be something wrong with my nitrous console as It throws an error age:

404 Not Found

The page you were looking for does not exist.

You may have mistyped the address or the page may have moved. You can return to our home page, or contact support if you can’t find what you're looking for.

am I doing something wrong?

**Comment by AnnJohn** [comment]
@abmoon Sorry for the delay here, but is this
