### ISSUE TITLE
I can't open the lab

### ISSUE THREAD

**Issue by Rami97** [learn-co-curriculum/first-lab-ruby-learn-cli-nitrous#12]
Hi,

I am in the session "First lab" right now, but I cannot manage to open the lab. The "open"-button somehow does not work. Please help me.

**Comment by AnnJohn** [comment]
@Rami97  Sorry for the trouble that you're having with the lab. For immediate help, please use the Ask a Question tool in Learn and someone from our chat support team will get back to you right away. Thanks!
