### ISSUE TITLE
First lab will not submit.

### ISSUE THREAD

**Issue by madifana** [learn-co-curriculum/first-lab-ruby-learn-cli-nitrous#14]
Every time I try to "learn submit" on the first lab, I get "Hmm...this doesn't appear to be a Learn lesson. Are you in the right directory?"  I am in the first-lab-ruby-learn-cli-nitrous-oc-001 directory, which is where I was automatically taken when I selected "open" in the first lab lesson.  Any idea what I might be missing?

**Comment by AnnJohn** [comment]
@madifana  Sorry for the trouble that you're having with the lab. For immediate help, please use the Ask a Question tool in Learn and someone from our chat support team will get back to you right away. Thanks!
