### ISSUE TITLE
cannot click "Open" tab, greyed

### ISSUE THREAD

**Issue by masbin** [learn-co-curriculum/first-lab-ruby-learn-cli-nitrous#16]
i reached the first lab lesson, but i find that the "open" tab is greyed and cannot be clicked to open the CLI in introus. when i manually open nitrous CLI IDE, i can't find the lesson folder under the lab folder, and i keep getting message "You don't appear to be in a Learn lesson's directory. Please cd to an appropriate directory and try again."

**Comment by AnnJohn** [comment]
@masbin  Sorry for the trouble that you're having with the lab. For immediate help, please use the Ask a Question tool in Learn and someone from our chat support team will get back to you right away. Thanks!
