### ISSUE TITLE
Continuing past first lab

### ISSUE THREAD

**Issue by PHILLIPKIMMEL** [learn-co-curriculum/first-lab-ruby-learn-cli-nitrous#18]
➜  first-lab-ruby-learn-cli-nitrous-q-000 git:(master) ✗ learn submit
Adding changes...
Committing changes...
Pushing changes to GitHub...
Submitting lesson...
Done.
➜  first-lab-ruby-learn-cli-nitrous-q-000 git:(master)

Result in console matches tutorial result, Local Build button is red, does not permit continuation of program

**Comment by AnnJohn** [comment]
Hi @PHILLIPKIMMEL sorry for the delay. Please use the Ask a Question tool in Learn and someone will get back to you right away to help with this issue.
