### ISSUE TITLE
Cant Launch Nitrous

### ISSUE THREAD

**Issue by mystycs** [learn-co-curriculum/first-lab-ruby-learn-cli-nitrous#23]
Getting the following error below if trying to launch Nitrous IDE through profile.

"Something went wrong. Please try again and contact support if you continue to see this error message."

And i get this error trying to launch Nitrous through a Lab.

![image](https://cloud.githubusercontent.com/assets/3004566/12028240/28f7b660-ada2-11e5-94f5-bf7bf66ce85e.png)

**Comment by AnnJohn** [comment]
Hi @mystycs sorry for the issue. This looks like it's something specific to you, so please use the Ask a Question tool in Learn and someone from our team will get back to your right away. Thanks!

**Comment by mystycs** [comment]
Just did, i am speaking to someone!

Thank you!

**Comment by AnnJohn** [comment]
Awesome!

**Comment by sammarcus** [comment]
@mystycs glad we were able to get this fixed over chat! have fun on Learn :)

**Comment by mystycs** [comment]
@sammarcus Thanks again!
