### ISSUE TITLE
Naviagting

### ISSUE THREAD

**Issue by kayc302** [learn-co-curriculum/first-lab-ruby-learn-cli-nitrous#24]
I need to navigate through lessons. Because I've somehow been put through previous labs I've already completed. And I want to find out more options about Learn co. I want to try to see what languages is there to learn and more general info. And payment information as well.

**Comment by AnnJohn** [comment]
Hi @kayc302 thanks for your questions. We use issues specifically for curriculum, so for your questions, please use the Ask a Question tool in Learn and someone will help you out with navigating lessons. You can also ask about payment and other options, you can use that too but will most likely be redirected to someone on our Admissions team. You can also email info@flatironschool.com for more info on payment and other options. Thanks
