### ISSUE TITLE
Can't advance but passed the lab

### ISSUE THREAD

**Issue by Turing-Tester** [learn-co-curriculum/first-lab-ruby-learn-cli-nitrous#25]
I was on the first lab offered and I have completed it. The problem is I completed it out of order and now I seem to have confused the system. I had to edit the edit-me.txt file which I did but I just went ahead and typed "learn submit" to the console (and Nitrous accepted it.) Now on learn.co it says I finished the lab but because I didn't do "learn" on its own first, Learn.co is telling me "your local tests have not been run." As such I cannot advance to the next track. When I click "next lesson" it sends me to the start of "The Learn Philosophy" again. How can this problem be remedied.

**Comment by AnnJohn** [comment]
Hi @DonnyFin this looks like a technical bug so for immediate help you can use the Ask a Question tool in Learn and someone from our support team will get back to you right away. Thanks!
