### ISSUE TITLE
Not getting error needed for completing lab

### ISSUE THREAD

**Issue by wclynch** [learn-co-curriculum/first-lab-ruby-learn-cli-nitrous#26]
I'm trying to test out the test suite but I' not receiving the expected error. Instead, I am getting a error that says: 

>  "Could not find proper version of rspec-core (3.3.2) in any of the sources
> Run `bundle install` to install missing gems."

Help me, please. :(

**Comment by AnnJohn** [comment]
Hi @wclynch for immediate, you can use the Ask a Question tool and someone will help you out.

In this case, type in "bundle install"  (no quotation marks) in your terminal or console and this should update the repo, and then you should be set. Thanks
