### ISSUE TITLE
Could not find proper version of rspec-core (3.3.2)

### ISSUE THREAD

**Issue by talgoldfus** [learn-co-curriculum/first-lab-ruby-learn-cli-nitrous#27]
Hi ,

I'm currently starting to use Learn adn encountered an error on the Intro to Learn - Nitrous - First Lab . I clicked on the open button and opened Nitrous but when i typed he 'learn' command in the CLI my error message was not the one that was described in the ReadMe file . My error message was as follows :  **_Could not find proper version of rspec-core (3.3.2) in any of the sources
Run `bundle install` to install missing gems._** . Only after typing in the CLI  'Bundle Install' was i able to get the right error and pass the test. 

See bellow the copy of my CLI : 

Current lab:   first-lab-ruby-learn-cli-nitrous-intro-to-learn
Lab directory: ~/code/labs/first-lab-ruby-learn-cli-nitrous-intro-to-learn
➜  first-lab-ruby-learn-cli-nitrous-intro-to-learn git:(master) learn
Could not find proper version of rspec-core (3.3.2) in any of the sources
Run `bundle install` to install missing gems.
➜  first-lab-ruby-learn-cli-nitrous-intro-to-learn git:(master) touch new-file
➜  first-lab-ruby-learn-cli-nitrous-intro-to-learn git:(master) ✗ learn
Could not find proper version of rspec-core (3.3.2) in any of the sources
Run `bundle install` to install missing gems.
➜  first-lab-ruby-learn-cli-nitrous-intro-to-learn git:(master) ✗ bundle install
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Installing coderay 1.1.0
Installing diff-lcs 1.2.5
Installing method_source 0.8.2
Installing slop 3.6.0
Installing pry 0.10.2
Installing rspec-support 3.3.0
Installing rspec-core 3.3.2
Installing rspec-expectations 3.3.1
Installing rspec-mocks 3.3.2
Installing rspec 3.3.0
Using bundler 1.10.5
Bundle complete! 2 Gemfile dependencies, 11 gems now installed.
Bundled gems are installed into ./.bundle.
➜  first-lab-ruby-learn-cli-nitrous-intro-to-learn git:(master) ✗ learn
First Lab:
  you made a change
Finished in 0.00172 seconds (files took 0.0886 seconds to load)
1 example, 0 failures
➜  first-lab-ruby-learn-cli-nitrous-intro-to-learn git:(master) ✗

**Comment by AnnJohn** [comment]
Hi @talgoldfus sorry for this issue.  Running 'bundle install' as you were instructed to do is the right way to solve this issue and in future labs you'll find this to be the case as well. We don't get into explaining 'bundle install' this early on but you'll learn all about it soon. Thanks.
