### ISSUE TITLE
Learn Submit not working

### ISSUE THREAD

**Issue by motoni2** [learn-co-curriculum/first-lab-ruby-learn-cli-nitrous#30]
Connection error. Please try again.
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/learn-web-1.4.2/lib/learn_web/client/user/me.rb:19:in `parse!': undefined method`status' for nil:NilC
lass (NoMethodError)
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/learn-web-1.4.2/lib/learn_web/client/user/me.rb:15:in `initialize'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/learn-web-1.4.2/lib/learn_web/client/user.rb:16:in`new'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/learn-web-1.4.2/lib/learn_web/client/user.rb:16:in `me'

**Comment by AnnJohn** [comment]
Hi @motoni2 sorry about this. This is a technical issue so could you file a bug report instead? If you hover over your profile pic in Learn, you'll see a menu option to report a bug. Thanks!
