### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by suzjlee** [learn-co-curriculum/first-lab-ruby-learn-cli-nitrous#31]
I accidentally terminated my prework-lab project in Nitrous and am having trouble retrieving it/relaunching.  Is there a way?

![screen shot 2016-03-09 at 5 17 19 pm](https://cloud.githubusercontent.com/assets/5523005/13654025/46182b26-e623-11e5-921c-dc35714c7f2a.png)

**Comment by AnnJohn** [comment]
hi @thesoozebutton can you use the Ask a Question tool for this? We use this space for issues specifically related to the curriculum content. Thanks!
