### ISSUE TITLE
Submitting first lab to Github fails

### ISSUE THREAD

**Issue by mwakipesile** [learn-co-curriculum/first-lab-ruby-learn-cli-nitrous#33]
I get an error when attempting to submit my first lab to Github. I tried three versions of Ruby, 2.1.5, 2.2.1, and 2.3.0 on Nitrous to no avail.

Learn version: 3.4.1
`learn submit` produces the following:
`Adding changes...
Committing changes...
It looks like you have no changes to commit. Will still try updating your submission...
Pushing changes to GitHub...
Submitting lesson...
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/learn-submit-1.1.7/lib/learn_submit/submission/git_interactor.rb:28:in`repo_name': undefined method `[]' for nil
:NilClass (NoMethodError)
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/learn-submit-1.1.7/lib/learn_submit/submission.rb:57:in`submit!'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/learn-submit-1.1.7/lib/learn_submit/submission.rb:25:in `create'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/learn-submit-1.1.7/lib/learn_submit/submission.rb:6:in`create'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/learn-submit-1.1.7/bin/learn-submit:15:in `<top (required)>'
        from /usr/local/opt/rbenv/versions/2.3.0/bin/learn-submit:23:in`load'
        from /usr/local/opt/rbenv/versions/2.3.0/bin/learn-submit:23:in `<main>'`

**Comment by AnnJohn** [comment]
hi @mwakipesile sorry about this issue. today we moved over to a different IDE that we built in-house. You can download the IDE and use that instead of nitrous. thanks!
