### ISSUE TITLE
Ring that turns green does not change even though I've completed the lesson

### ISSUE THREAD

**Issue by ArtyMinimal** [learn-co-curriculum/first-lab-ruby-learn-cli-nitrous#35]
I did both learn to run program and learn submit to get it to pass.
But ring for run program does not turn green.
I can't get to the lesson after intro to learn

**Comment by AnnJohn** [comment]
hi @ArtyMinimal sorry for the issue you're having. Can you please file a bug report for this as we reserve this space for issues specifically related to the content of the lessons. If you hover over your profile pic in Learn, you'll see an option to file a bug report. thanks!
