### ISSUE TITLE
Whoops! There was a problem opening this lab

### ISSUE THREAD

**Issue by konayuki617** [learn-co-curriculum/first-lab-ruby-learn-cli-nitrous#36]
I've been stuck in the first lab for a couple of days now. Everytime I try to open it I get an alert with the message in the title. Can anyone provide some insight? I cannot continue this course.

**Comment by AnnJohn** [comment]
hi @konayuki617 we sunsetted Nitrous recently and have switched to a development environment that we built in-house. You can go to https://learn.co/ide to download it. Thanks.

Also you can email support@learn.co for help
