### ISSUE TITLE
when i click open get whoops

### ISSUE THREAD

**Issue by m00k3y** [learn-co-curriculum/first-lab-ruby-learn-cli-nitrous#8]
I click Open on the First Lab page
![image](https://cloud.githubusercontent.com/assets/15205992/10597140/43d93760-76b1-11e5-9b20-fd8132d8a7e5.png)

and I get this:

![image](https://cloud.githubusercontent.com/assets/15205992/10597144/511cd29c-76b1-11e5-981e-ca05c37b504a.png)

help?

Thanks!

Mike

**Comment by m00k3y** [comment]
sorry a bit more info - tried with both chrome and safari and get same results.

**Comment by AnnJohn** [comment]
Hi @m00k3y sorry for the issue you're having, but for immediate help, please use the "Ask a Question" chat in Learn and someone will help you right away. Thanks!
